# This workflow will delete the respective fork branch when a PR authored by 'wso2-jenkins-bot' is merged/closed.

name: 🧹 Sync PRs Fork Branch Deleter

on:
  pull_request:
    types: [ closed ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    # Check whether the PR was authored by 'wso2-iam-bot'.
    if: github.event.pull_request.head.repo.owner.login == 'wso2-iam-bot'
    runs-on: ubuntu-latest

    steps:
      # Check out the fork of 'wso2-iam-bot' user
      - uses: actions/checkout@v5
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          token: ${{ secrets.PR_AUTOMATION_BOT_TOKEN }}

      - name: Show information about the PR and Branch
        run: |
          echo "PR authored by: ${{ github.event.pull_request.user.login }}"
          echo "Branch to be deleted: ${{ github.event.pull_request.head.ref }}"

      - name: Delete Fork Branch of wso2-jenkins-bot
        run: git push -d origin ${{ github.event.pull_request.head.ref }}
